# File paths
data_paths:
  outbound_folder: "nebula/outbound"
  reference_file: "nebula/ref/dmsp.csv"

# Column renaming mapping
column_mapping:
  Loại phiếu: LoaiPhieu

# # Data type conversions
# dtype_mapping:
#   date_column: datetime64

# # Merge settings
# merge:
#   on:
#     - product_id
#   how: inner